# Generated by Django 4.2.7 on 2024-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='products',
            field=models.ManyToManyField(to='api.products'),
        ),
    ]
